line-length = 88

# Включаем проверки
select = [
    "E",      # PEP8 ошибки
    "F",      # потенциальные баги и undefined names
    "C90",    # проверка сложности функций
    "I",      # импорты
]

# Игнорируем менее критичные предупреждения
ignore = [
    "E203",   # пробел перед :, допустимо
    "E501",   # длинные строки
]

# Игнорирование специфичных предупреждений для отдельных файлов
[per-file-ignores]
"src/power.py" = ["E721"]   # для проверки isinstance (не использовать bare except)
