[project]
name = "labs"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"

[dependency-groups]
dev = [
    "mypy>=1.18.2",
    "pytest>=8.4.2",
    "ruff>=0.13.3",
    "pre-commit>=4.3.0"
]
